name: Deploy main to Portainer

on:
  push:
    branches:
      - main

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Portainer redeploy
        run: |
          curl -v -f -X PUT \
            "https://portainer.rafalcaban.com/api/stacks/12/git/redeploy?endpointId=3" \
            -H "X-API-Key: ${{ secrets.PORTAINER_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"RepullImageAndRedeploy": true}'
